# Generated by Django 4.1.1 on 2022-09-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-id'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Структура', 'verbose_name_plural': 'Структура'},
        ),
        migrations.AddField(
            model_name='tenders',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tender_order', to='tenders.orders', verbose_name='Победитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название '),
        ),
    ]
