# Generated by Django 4.1.1 on 2022-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_tenders_customer_alter_tenders_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'Модератор'), ('CUSTOMER', 'Заказчик'), ('EXECUTOR', 'Исполнитель')], default='EXECUTOR', max_length=255, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создано'), ('ON_APPROVE', 'На согласовании'), ('FINISHED', 'Завершено'), ('REJECTED', 'Отклонено')], default='CREATED', max_length=255, verbose_name='Статус'),
        ),
    ]
