# Generated by Django 4.1.1 on 2022-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tendersfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
